version: '3.8'
services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    expose:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
      NEO4J_dbms_memory_heap_initial__size: "512M"
      NEO4J_dbms_memory_heap_max__size: "2G"
      NEO4J_server_config_strict__validation_enabled: "false"
    volumes:
      - neo4j_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.neo4j.entrypoints=http
      - traefik.http.routers.neo4j.rule=Host(`neo4j.ahoum.com`)
      - traefik.http.routers.neo4j.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.neo4j-secure.entrypoints=https
      - traefik.http.routers.neo4j-secure.rule=Host(`neo4j.ahoum.com`)
      - traefik.http.routers.neo4j-secure.service=neo4j
      - traefik.http.routers.neo4j-secure.tls=true
      - traefik.http.routers.neo4j-secure.tls.certresolver=letsencrypt
      - traefik.http.services.neo4j.loadbalancer.server.port=7474

volumes:
  neo4j_data:
