version: '3.8'
services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
      NEO4J_dbms_memory_heap_initial__size: "512M"
      NEO4J_dbms_memory_heap_max__size: "2G"
    volumes:
      - neo4j_data:/data

  api:
    build: .
    container_name: preference_api
    depends_on:
      - neo4j
    ports:
      - "8002:8000"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: "${NEO4J_USER}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
      OPENAI_API_BASE: "${OPENAI_API_BASE}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      MODEL_NAME: "${NEBIUS_MODEL_NAME}"
      EMBEDDING_MODEL_NAME: "${NEBIUS_EMBEDDING_MODEL_NAME}"
      GRAPHITI_LLM_TIMEOUT: "50"
    volumes:
      - .:/app

  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"

volumes:
  neo4j_data: 
